[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
# tracing = { workspace = true }
# tracing-subscriber = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart", "stream"] }
helpers = { workspace = true, features = ["jwt", "rand"] }
tokio = { version = "1.44.1", features = ["full"] }
clap = { version = "4.5.32", features = ["derive"] }
indicatif = "0.17.11"
console = { version = "0.15.11", default-features = false, features = [
  "ansi-parsing",
] }
tar = "0.4.44"
rust-embed = "8.6.0"
log = "0.4.27"
env_logger = "0.11.7"
dialoguer = "0.11.0"
dirs = "6.0.0"
